name: kn05-c

volumes:
  kn05-named-vol:

services:
  nginx1:
    image: nginx
    volumes:
      # volume (long syntax version)
      - type: volume
        source: kn05-named-vol
        target: /data
      # bind mount
      - type: bind
        source: ./bindmount
        target: /usr/share/nginx/html
      # tmpfs
      - type: tmpfs
        target: /tmp/tmpfs

  nginx2:
    image: nginx
    volumes:
      # volume (short syntax version)
      - kn05-named-vol:/data